-- Generated by nwg-displays on 2026-07-26 at 17:05:16. Do not edit manually.

hl.monitor({
    output = "desc:ASUSTek COMPUTER INC XG27JCG TCLMQV067168",
    mode = "5120x2880@119.99",
    position = "0x0",
    scale = 2.0000000000000004
})
hl.monitor({
    output = "desc:ASUSTek COMPUTER INC XG27ACDNG SALMAS019558",
    mode = "2560x1440@359.98",
    position = "2560x0",
    scale = 1.0
})
