#!/usr/bin/env lua

-- Convert dBm to watts:
-- watts = 10 ^ ((dBm - 30) / 10)

local function usage()
    io.stderr:write(
        string.format("Usage: %s <dBm>\n", arg[0] or "dbm_to_watts")
    )
end

if #arg ~= 1 then
    usage()
    os.exit(1)
end

local dbm = tonumber(arg[1])

if dbm == nil then
    io.stderr:write("Error: dBm must be a number.\n")
    os.exit(1)
end

local watts = 10 ^ ((dbm - 30) / 10)

print(string.format("%.3f dBm = %.9g W", dbm, watts))
